/*
 *  UI Gadget
 *
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Contact: Jayoun Lee <airjany@samsung.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef __UG_LIST_H__
#define __UG_LIST_H__

const char *UG_LIST[] = {
		"helloUG-efl",
		"activesync-efl",
		"alarm-efl",
		"bookmark-add-efl",
		"browser-user-agent-efl",
		"calendar-detail-efl",
		"calendar-edit-efl",
		"calendar-efl",
		"calendar-settings-efl",
		"camera-efl",
		"cert-selection-ug-efl",
		"contacts-details-efl",
		"contacts-list-efl",
		"contacts-settings-efl",
		"contacts-tabui-efl",
		"csc-pre-configuration-efl",
		"csc-sim-auto-setting-select-efl",
		"csc-sim-auto-setting-test-efl",
		"csc-verifier-efl",
		"dialer-efl",
		"email-block-efl",
		"email-composer-efl",
		"email-filter-efl",
		"email-setting-efl",
		"email-account-efl",
		"email-docsearch-efl",
		"email-mailbox-efl",
		"email-viewer-efl",
		"emergency-msg-setting-efl",
		"eml-viewer-efl",
		"find-my-mobile-efl",
		"gallery-efl",
		"google-service-account",
		"help-efl",
		"image-viewer-efl",
		"install-voice-efl",
		"kies-via-wifi",
		"lockscreen-options",
		"map-efl",
		"msg-composer-efl",
		"msg-setting-efl",
		"msg-viewer-efl",
		"music-player-efl",
		"myfile-detail-efl",
		"myfile-efl",
		"phonelog-efl",
		"phone-tabui-efl",
		"setting-about-efl",
		"setting-accessibility-efl",
		"setting-accessory-efl",
		"setting-allshare-cast-efl",
		"setting-allshare-efl",
		"setting-blockingmode-efl",
		"setting-bluetooth-efl",
		"setting-call-efl",
		"setting-cloud-efl",
		"setting-datausage-efl",
		"setting-developeroption-efl",
		"setting-display-efl",
		"setting-dock-efl",
		"setting-drivingmode-efl",
		"setting-fileview-efl",
		"setting-firewall-efl",
		"setting-font-efl",
		"setting-gallery-efl",
		"setting-homescreen-efl",
		"setting-ioprofile-efl",
		"setting-joyn-efl",
		"setting-ledindicator-efl",
		"setting-location-efl",
		"setting-manage-applications-efl",
		"setting-memory-efl",
		"setting-mmc-encryption-efl",
		"setting-mobileap-efl",
		"setting-motion-efl",
		"setting-myaccount-efl",
		"setting-myplace-efl",
		"setting-network-efl",
		"setting-nfc-efl",
		"setting-password-efl",
		"setting-phone-efl",
		"setting-plugin-efl",
		"setting-powersaving-efl",
		"setting-privacy-efl",
		"setting-profile-efl",
		"setting-readytoshare-efl",
		"setting-reset-efl",
		"setting-security-efl",
		"setting-shortcut-efl",
		"setting-storage-efl",
		"setting-synchronise-efl",
		"setting-time-efl",
		"setting-wifidirect-efl",
		"smemo-efl",
		"speeddial-efl",
		"svoice-setting-efl",
		"video-player-view-efl",
		"video-store-view-efl",
		"video-store-voucherInfo-efl",
		"wallpaper-viewer-efl",
		"webapp-detail-efl",
		"wifi-efl-UG",
		"worldclock-efl",
		"isfsetting-efl",
		"setting-voice-efl",
		"setting-encrypting-efl",
		"setting-manage-certificates-efl",
		"cert-svc-ui",
		"setting-tagbuddy-efl",
		"call-help-try",
		"quickpanel-setting-efl",
		"citylist-efl",
		"cam-external-viewer-efl",
		"ncr-efl",
		"ise-multilingual-help-efl",
		"browser-helpui-efl",
		"setting-sim-manager-efl",
		"quickpanel-help-efl",
		"setting-personalpage-efl",
		"lockscreen-help",
		"setting-locktype-efl",
		"setting-flightmode-efl",
		"setting-emergency-efl",
		"setting-netrestriction-mode-efl",
		"setting-galleryapp-efl",
		"quickcommand-setting-efl",
		"setting-palmmotion-efl",
		"setting-easymode-efl",
		"setting-color-theme-efl",
		"ise-japanese-help-efl"
};

#endif		/* __UG_LIST_H__ */
